### ISSUE TITLE
New FireFox v.27.0 Arrow Problem

### ISSUE THREAD

**Issue by swiftusa** [chinchang/hint.css#70]
Hello,
hint.css has been my very favorite tooltip script. I had been using hint for over a month.

I was using FireFox v.26.0 with no problems, but today morning FireFox automatically upgraded to v.27.0.

Now the shape of the tooltip arrow is crumbled, but the shape of the box is fine. This problem is only in FireFox and not in Chrome. I then tested this on a different computer with FireFox v.26.0 and the tooltip arrow was okay, I then upgraded the FireFox  to v.27.0 and the same problem is replicated.

Can you please test hint.css on FireFox v.27.0 and share your experience?

Best Regards,
Sanson

**Comment by jonataswalker** [comment]
+1

**Comment by chinchang** [comment]
Is this issue still present on Firefox?

**Comment by jonataswalker** [comment]
Yeap. I've made the changes suggested and the triangle hint became much better.

**Comment by jonataswalker** [comment]
After all, the changes made by @swiftusa looks fine in Firefox but looks horrible in IE 11 so I've made some tests.

If I set:
```css
.hint::before, [data-hint]::before {
    border-style: inset;
 }
```
I have some different colors on triangle. [Plunker](http://plnkr.co/edit/Wf57tzhHpTidqKPD0CyE?p=preview).

`-moz-transform: scale(.9999);` is not an option since it conflicts with `transform: translateY(...);`

So [I ended up (plunker)](http://plnkr.co/edit/fYQ1mO2pmJEFhrOr9X6I?p=preview) changing to:
```css
.hint::before, [data-hint]::before {
    border: 8px solid transparent;
}
/**and some other changes***/
```
Tested in Firefox, Chrome and IE 11.
